[package]
name = "rust-fsm-graph"
version = "0.1.0"
authors = ["Jonas Berlin <xkr47@outerspace.dyndns.org>"]
edition = "2018"

[dependencies]
proc-macro2 = "1.0"

[dependencies.syn]
version = "1.0"
features = [ "full", "parsing" ]
