[package]
name = "rust-fsm-graph"
version = "0.2.0"
authors = ["Jonas Berlin <xkr47@outerspace.dyndns.org>"]
edition = "2021"

[dependencies]
itertools = "0.10"
linked_hash_set = "0.1"
linked-hash-map = "0.5"

[dependencies.syn]
version = "1.0"
features = [ "full", "parsing" ]
